---
title: "Bengali Cue-Weighting"
author: "Molly Babel and Aurmita Mitra"
date: "15/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
df <- read_csv("bengali_20210415.csv")
head(df)
```

```{r}

df <- df %>%
  mutate(stim = str_replace(stimulus, ".wav", "")) %>%
  #filter(block == "a") %>%
  #mutate(talker = extract_numeric(stimulus))
  #  filter(is.na(categorized_as) == TRUE,
  #       is.na(categorized_as) == FALSE) %>%
  separate(stim, into = c("stuff", "SpectralStep", "dur", "DurationStep"), sep="_") %>%
  filter(dur == "dur") %>%
  select(participant, rt, stimulus, categorized_as, trial_index, SpectralStep, DurationStep) %>%
  mutate(condition = if_else(str_sub(categorized_as, 1, 1) == "h", "heart/hurt", "staff/stuff"))
  
#View(df)
```

```{r}
h.df <- df %>%
  filter(condition == "heart/hurt") %>%
  mutate(HeartResponse = if_else(categorized_as == "heart", 1, 0))

h.df$SpectralStep <- as.numeric(h.df$SpectralStep)
h.df$DurationStep <- as.numeric(h.df$DurationStep)
h.df
```

```{r}
h.df %>%
  group_by(SpectralStep, DurationStep) %>%
  summarize(PropHeart = mean(HeartResponse)) %>%
  ggplot(aes(x=SpectralStep, y = DurationStep, fill = PropHeart)) +
  geom_tile()
```

```{r}
s.df <- df %>%
  filter(condition == "staff/stuff") %>%
  mutate(StaffResponse = if_else(categorized_as == "staff", 1, 0))

s.df$SpectralStep <- as.numeric(s.df$SpectralStep)
s.df$DurationStep <- as.numeric(s.df$DurationStep)
s.df
```

```{r}
s.df %>%
  group_by(SpectralStep, DurationStep) %>%
  summarize(PropStaff = mean(StaffResponse)) %>%
  ggplot(aes(x=SpectralStep, y = DurationStep, fill = PropStaff)) +
  geom_tile()
```